In [6]:
import pandas as pd
user_usage = pd.read_csv("user_usage.csv")
user_device = pd.read_csv("user_device.csv")
devices = pd.read_csv("android_devices.csv")
devices.rename(columns={"Retail Branding": "manufacturer"}, inplace=True)

There are Three main methods, *Join, Merge, and Concat*. However, Concat is mainly for series and opperations in a single dimension, so we are not goinh to focus on it today. Lets first look at *Join*

## Join
Join is the simplest and the most intuitive method for combining two dataframe. It works by combining the data frames by row index. Let's take a look!

In [7]:
print(user_usage.shape)
user_usage.head()

(240, 4)


outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id
0                    21.97                    4.82     1557.33   22787
1                  1710.08                  136.88     7267.55   22788
2                  1710.08                  136.88     7267.55   22789
3                    94.46                   35.17      519.12   22790
4                    71.59                   79.26     1557.33   22792

In [8]:
print(user_device.shape)
user_device.head()

(272, 6)


use_id  user_id platform  platform_version     device  use_type_id
0   22782    26980      ios              10.2  iPhone7,2            2
1   22783    29628  android               6.0    Nexus 5            3
2   22784    28473  android               5.1   SM-G903F            1
3   22785    15200      ios              10.2  iPhone7,2            3
4   22786    28239  android               6.0  ONE E1003            1

In [9]:
result=user_usage.join(user_device,how='left',lsuffix='**')
print(result.shape)
result.head()


(240, 10)


outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id**  \
0                    21.97                    4.82     1557.33     22787   
1                  1710.08                  136.88     7267.55     22788   
2                  1710.08                  136.88     7267.55     22789   
3                    94.46                   35.17      519.12     22790   
4                    71.59                   79.26     1557.33     22792   

   use_id  user_id platform  platform_version     device  use_type_id  
0   22782    26980      ios              10.2  iPhone7,2            2  
1   22783    29628  android               6.0    Nexus 5            3  
2   22784    28473  android               5.1   SM-G903F            1  
3   22785    15200      ios              10.2  iPhone7,2            3  
4   22786    28239  android               6.0  ONE E1003            1

In [10]:
result=user_usage.join(user_device,how='right',lsuffix='**')
print(result.shape)
result.head()

(272, 10)


outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id**  \
0                    21.97                    4.82     1557.33   22787.0   
1                  1710.08                  136.88     7267.55   22788.0   
2                  1710.08                  136.88     7267.55   22789.0   
3                    94.46                   35.17      519.12   22790.0   
4                    71.59                   79.26     1557.33   22792.0   

   use_id  user_id platform  platform_version     device  use_type_id  
0   22782    26980      ios              10.2  iPhone7,2            2  
1   22783    29628  android               6.0    Nexus 5            3  
2   22784    28473  android               5.1   SM-G903F            1  
3   22785    15200      ios              10.2  iPhone7,2            3  
4   22786    28239  android               6.0  ONE E1003            1

In [11]:
result[240:245]

outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id**  \
240                      NaN                     NaN         NaN       NaN   
241                      NaN                     NaN         NaN       NaN   
242                      NaN                     NaN         NaN       NaN   
243                      NaN                     NaN         NaN       NaN   
244                      NaN                     NaN         NaN       NaN   

     use_id  user_id platform  platform_version          device  use_type_id  
240   23022    25498      ios              10.2         iPad5,3            2  
241   23023    29647  android               7.0   ONEPLUS A3003            1  
242   23024    28637  android               6.0  MotoE2(4G-LTE)            1  
243   23025    29715      ios              10.1       iPhone6,2            3  
244   23026    22763  android               6.0       ONE A2003            1

In [12]:
result=user_usage.join(user_device,how='inner',lsuffix='**')
print(result.shape)
result.head()
#inner is the intersection of the two dataframes, 
#so the result is the same as the left join

(240, 10)


outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id**  \
0                    21.97                    4.82     1557.33     22787   
1                  1710.08                  136.88     7267.55     22788   
2                  1710.08                  136.88     7267.55     22789   
3                    94.46                   35.17      519.12     22790   
4                    71.59                   79.26     1557.33     22792   

   use_id  user_id platform  platform_version     device  use_type_id  
0   22782    26980      ios              10.2  iPhone7,2            2  
1   22783    29628  android               6.0    Nexus 5            3  
2   22784    28473  android               5.1   SM-G903F            1  
3   22785    15200      ios              10.2  iPhone7,2            3  
4   22786    28239  android               6.0  ONE E1003            1

In [13]:
result=user_usage.join(user_device,how='outer',lsuffix='**')
print(result.shape)
result[239:244]
#outer is the union of the two dataframes, 
#so the result is the same as the right join

(272, 10)


outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id**  \
239                    488.7                  906.92     3089.85   25220.0   
240                      NaN                     NaN         NaN       NaN   
241                      NaN                     NaN         NaN       NaN   
242                      NaN                     NaN         NaN       NaN   
243                      NaN                     NaN         NaN       NaN   

     use_id  user_id platform  platform_version          device  use_type_id  
239   23021    28220  android               6.0        SM-G930F            1  
240   23022    25498      ios              10.2         iPad5,3            2  
241   23023    29647  android               7.0   ONEPLUS A3003            1  
242   23024    28637  android               6.0  MotoE2(4G-LTE)            1  
243   23025    29715      ios              10.1       iPhone6,2            3

In [14]:
result=user_usage.join(user_device,how='cross',lsuffix='**')
print(result.shape)
result.head()
#this parirs every row of the left dataframe with every row of the right dataframe,
#thus forming an n*m dataframe. 
#240*272=65280

(65280, 10)


outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id**  \
0                    21.97                    4.82     1557.33     22787   
1                    21.97                    4.82     1557.33     22787   
2                    21.97                    4.82     1557.33     22787   
3                    21.97                    4.82     1557.33     22787   
4                    21.97                    4.82     1557.33     22787   

   use_id  user_id platform  platform_version     device  use_type_id  
0   22782    26980      ios              10.2  iPhone7,2            2  
1   22783    29628  android               6.0    Nexus 5            3  
2   22784    28473  android               5.1   SM-G903F            1  
3   22785    15200      ios              10.2  iPhone7,2            3  
4   22786    28239  android               6.0  ONE E1003            1

## Merge
Merge is a more versatial, powerful form of join. It allows us to combine data sets with regards to columns

In [15]:
result = pd.merge(user_usage,
                 user_device[['use_id', 'platform', 'device']],
                 on='use_id')
print(result.shape)
result.head()

(159, 6)


outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id  \
0                    21.97                    4.82     1557.33   22787   
1                  1710.08                  136.88     7267.55   22788   
2                  1710.08                  136.88     7267.55   22789   
3                    94.46                   35.17      519.12   22790   
4                    71.59                   79.26     1557.33   22792   

  platform    device  
0  android  GT-I9505  
1  android  SM-G930F  
2  android  SM-G930F  
3  android     D2303  
4  android  SM-G361F

What is happending here? The join method defaults to how=left when it is applied to a data set, whereas merge defaults to inner, which is the intersection between the two dataframes. Lets take a look by counting the number of matching keys below. 

In [16]:
a=user_device['use_id']
b=user_usage['use_id']
count=0
#counts the number of matching user ids
#as these are customer ids, we can assume no repeating elements in a given dataframe
for x in a:
    temp=False
    for y in b:
        if y==x:
            temp=True
            break
    if temp:
        count+=1
print(count)


159


In [17]:
print(user_device.shape)
print(user_usage.shape)
print(user_device['use_id'].unique().shape)
user_usage['use_id'].unique().shape


(272, 6)
(240, 4)
(272,)


(240,)

But why is this different from join's how=inner? Because remember that Join uses indices and merge uses columns. left was the same as inner for join because 272>240, thus there were 240 instances of overlaps in row indicies.

Let's take a look at how all the other methods play out in merge 

In [18]:
result = pd.merge(user_usage,
                 user_device[['use_id', 'platform', 'device']],
                 on='use_id', how='left')
print(result.shape)
print(result[:2])
result[200:205]


(240, 6)
   outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id  \
0                    21.97                    4.82     1557.33   22787   
1                  1710.08                  136.88     7267.55   22788   

  platform    device  
0  android  GT-I9505  
1  android  SM-G930F  


outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id  \
200                    28.79                   29.42     3114.67   23988   
201                   616.56                   99.85     5414.14   24006   
202                   339.09                  136.88     9854.79   24037   
203                   335.03                  105.44      634.28   24180   
204                  1407.98                  245.53     5140.96   24190   

    platform device  
200      NaN    NaN  
201      NaN    NaN  
202      NaN    NaN  
203      NaN    NaN  
204      NaN    NaN

In [19]:
result = pd.merge(user_usage,
                 user_device[['use_id', 'platform', 'device']],
                 on='use_id', how='right')
print(result.shape)
result[239:244]

(272, 6)


outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id  \
239                    63.56                   26.87     9344.00   23021   
240                      NaN                     NaN         NaN   23022   
241                   157.33                    8.87     1557.33   23023   
242                    70.34                   18.00      212.64   23024   
243                      NaN                     NaN         NaN   23025   

    platform          device  
239  android        SM-G930F  
240      ios         iPad5,3  
241  android   ONEPLUS A3003  
242  android  MotoE2(4G-LTE)  
243      ios       iPhone6,2

In [20]:
result.head()

outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id  \
0                      NaN                     NaN         NaN   22782   
1                      NaN                     NaN         NaN   22783   
2                      NaN                     NaN         NaN   22784   
3                      NaN                     NaN         NaN   22785   
4                      NaN                     NaN         NaN   22786   

  platform     device  
0      ios  iPhone7,2  
1  android    Nexus 5  
2  android   SM-G903F  
3      ios  iPhone7,2  
4  android  ONE E1003

In [21]:
result = pd.merge(user_usage,
                 user_device[['use_id', 'platform', 'device']],
                 on='use_id', how='outer', indicator=True)
result.shape
#(240+272)-159=353

(353, 7)

Merge can also use indices like join specificying the options left_index=True, right_index=True

## Practice:
Use merge to make a new df of "device" type and "outgoing_mins_per_month" based on index

In [22]:
result=pd.merge(user_usage['outgoing_mins_per_month'],user_device['device'],how='outer',left_index=True, right_index=True)
print(result.shape)
result.head()

(272, 2)


outgoing_mins_per_month     device
0                    21.97  iPhone7,2
1                  1710.08    Nexus 5
2                  1710.08   SM-G903F
3                    94.46  iPhone7,2
4                    71.59  ONE E1003